baseURL: https://noborus.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Noboru Saito's page
theme: hugo-theme-relearn
googleAnalytics: UA-136434199-2
enableGitInfo: true

languages:
  ja:
    languageName: "Japanese"
    title: "斉藤登のページ"
  en:
    languageName: "English"
    title: "Noboru Saito's page"

outputs:
  home: ["HTML", "RSS", "JSON"]

imaging:
  quality: 99

params:
  description: "Noboru Saito's site"
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  themeVariant: "relearn-light"
  search: true
  disableLandingPageButton: false
  themeVariant: 'my-custom-variant'

menu:
  shortcuts:
    - name: "<i class='fas fa-tags'></i> Tags"
      url: "/tags"
    - name: "<i class='fas fa-list'></i> Categories"
      url: "/categories"

markup:
  goldmark:
    renderer:
      unsafe: true