baseURL: https://noborus.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Noboru Saito's page
theme: hugo-theme-relearn
googleAnalytics: G-CGNLN23TRR

languages:
  en:
    languageName: "English"
    title: "Noboru Saito's page"
    weight: 1
    menu:
      shortcuts:
      - name: "<i class='fas fa-tags'></i> Tags"
        url: "/tags"
      - name: "<i class='fas fa-list'></i> Categories"
        url: "/categories"
  ja:
    languageName: "Japanese"
    title: "斉藤登のページ"
    weight: 2
    menu:
      shortcuts:
      - name: "<i class='fas fa-tags'></i> タグ"
        url: "/tags"
      - name: "<i class='fas fa-list'></i> カテゴリー"
        url: "/categories"

module:
  mounts:
    - source: content
      target: content
      lang: 'ja'
    - source: content
      target: content
      lang: 'en'

outputs:
  home: ["HTML", "RSS", "JSON"]

imaging:
  quality: 99

params:
  description: "Noboru Saito's site"
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  additionalContentLanguage:
    - "en"
    - "ja"
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  themeVariant: "relearn-light"
  search: true
  disableLandingPageButton: false
  themeVariant: 'my-custom-variant'
  disableShortcutsTitle: true
  collapsibleMenu: true
  images: /images/logo.svg

markup:
  goldmark:
    renderer:
      unsafe: true