baseURL: https://noborus.github.io/
languageCode: ja
defaultContentLanguage: ja
title: Noboru Saito's page
theme: cupper-hugo-theme
googleAnalytics: UA-136434199-2
enableGitInfo: true

taxonomies:
  tag: tags
  category: categories
permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: "Noboru Saito's site"
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  customCss:
    - css/local.css
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: trdsql
      url: /trdsql/
      weight: 3
    - name: ov
      url: /ov/
      weight: 4
    - name: Categories
      url: /categories/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6
    - name: About
      url: /about/
      weight: 7
    - name: RSS
      url: /index.xml
      weight: 8

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
